### ISSUE TITLE
生成changelog的表格的markdown语法有点问题

### ISSUE THREAD

**Issue by tyler4400** [luoxue-victor/commitlint#1]
![image](https://user-images.githubusercontent.com/8841273/69695816-9d0d4000-1118-11ea-960c-60b83a61de9e.png)

**Comment by luoxue-victor** [comment]
你用的是什么编译器？我用的 vscode 跟 有道云笔记上试了都没有问题。我修改了一个版本，把头部的两个 | 去掉了，你再试一下～

**Comment by tyler4400** [comment]
我在typroa和webstorm都不行

github这里可以吗？ 也不行。
|范围|描述|commitId|
--|--|--
 全局 | 增加commitlint功能 | 64c6521

你不因该去掉头部的 `|` ,应该给body的两边都加上，像这样,并且表格有个回车，`|`之间有空格

| 范围|描述 |commitId |
| -- |-- | -- |
 |全局 | 增加commitlint功能 | 64c6521 |

**Comment by luoxue-victor** [comment]
我的github上的chengelog就是这样生成的～，可以留个微信交流一下吗？
