### ISSUE TITLE
Cannot find module 'right-pad'

### ISSUE THREAD

**Issue by kkkman22** [luoxue-victor/commitlint#3]
![image](https://user-images.githubusercontent.com/23480907/81462990-cf06f000-91e8-11ea-9bf7-09cfda6f71c4.png)

**Comment by ishowman** [comment]
the same error。Here are the steps:
- vue add your plugin
-  npm run cz
- report the error`Cannot find module 'right-pad'`

**Comment by BoBoooooo** [comment]
the same error , somebody know how to fix it ?

**Comment by luoxue-victor** [comment]
fixed
